# Generated by Django 5.0.6 on 2024-06-29 14:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('site_address', models.TextField()),
                ('inquiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='constructionlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructionlevelname', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='constructiontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='employeeregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employeeid', models.CharField(blank=True, max_length=5, unique=True)),
                ('emailid', models.EmailField(max_length=254)),
                ('phonenum', models.BigIntegerField()),
                ('dateofbirth', models.DateField()),
                ('permanentaddress', models.TextField()),
                ('presentaddress', models.TextField()),
                ('gender', models.CharField(max_length=15)),
                ('bloodgroup', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('bankacnum', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('aadharcard', models.BigIntegerField()),
                ('pancard', models.CharField(max_length=10)),
                ('pfnum', models.CharField(max_length=22)),
                ('pfeligibledate', models.DateField()),
                ('licencenum', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='finaldrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('clientname', models.CharField(max_length=100)),
                ('executiveenggname', models.CharField(max_length=100)),
                ('dateofsubmission', models.DateField()),
                ('drawingcount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mastermateriallist',
            fields=[
                ('materialid', models.AutoField(primary_key=True, serialize=False)),
                ('materialname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoughDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('executive_engg_name', models.CharField(max_length=100)),
                ('date_of_submission', models.DateField()),
                ('drawing_count', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='unitmeasurement',
            fields=[
                ('unitmeasurementid', models.AutoField(primary_key=True, serialize=False)),
                ('unitmeasurementname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('landline_number', models.IntegerField()),
                ('registered_office_address', models.TextField()),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('gst_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[0-9]{1}[Z]{1}[0-9]{1}$')])),
                ('organization_type', models.CharField(choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Limited Liability Partnership', 'Limited Liability Partnership'), ('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company'), ('Others', 'Others')], max_length=50)),
                ('nature_of_business', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('progress', models.IntegerField(default=0)),
                ('worker_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='worktypes',
            fields=[
                ('worktypeid', models.AutoField(primary_key=True, serialize=False)),
                ('worktypename', models.CharField(max_length=40)),
                ('workdescription', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ClientInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('follow_off_date', models.DateField()),
                ('remark', models.TextField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.client_registration')),
                ('construction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.constructiontype')),
                ('representative_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.employeeregistration')),
            ],
        ),
        migrations.AddField(
            model_name='client_registration',
            name='representative_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.employeeregistration'),
        ),
        migrations.CreateModel(
            name='approvedinquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotarea', models.IntegerField()),
                ('constructionarea', models.IntegerField()),
                ('constructioncost', models.IntegerField()),
                ('totalcost', models.IntegerField()),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.client_registration')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.constructiontype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.employeeregistration')),
            ],
        ),
        migrations.CreateModel(
            name='brandlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=25)),
                ('materialnames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.mastermateriallist')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('houseno', models.CharField(max_length=50)),
                ('roadname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=350)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.approvedinquiry')),
            ],
        ),
        migrations.CreateModel(
            name='masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.approvedinquiry')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.site')),
            ],
        ),
        migrations.CreateModel(
            name='Taskttransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(default='assign', max_length=50)),
                ('assign_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_three', to='construction.employeeregistration')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.employeeregistration')),
                ('assign_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_two', to='construction.employeeregistration')),
                ('customersid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.masterdata')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.constructionlevel')),
            ],
        ),
        migrations.CreateModel(
            name='internaltransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executiveengineer', models.CharField(max_length=50)),
                ('executiveengineernum', models.BigIntegerField()),
                ('sourceclientname', models.CharField(max_length=50)),
                ('sourceaddress', models.TextField()),
                ('destinationclientname', models.CharField(max_length=50)),
                ('destinationaddress', models.TextField()),
                ('vehiclename', models.CharField(max_length=50)),
                ('vehiclenum', models.CharField(max_length=15)),
                ('drivername', models.CharField(max_length=50)),
                ('drivernum', models.BigIntegerField()),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('transferdate', models.DateTimeField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.brandlist')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.mastermateriallist')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.unitmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='addmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateTimeField(default=datetime.datetime.now)),
                ('transferdate', models.DateField()),
                ('specifications', models.TextField()),
                ('quantitys', models.IntegerField(blank=True, null=True)),
                ('requirementby', models.CharField(max_length=200)),
                ('requirementto', models.CharField(max_length=200)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.approvedinquiry')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.category')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.mastermateriallist')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.site')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.unitmeasurement')),
            ],
        ),
    ]
