# Generated by Django 4.2.1 on 2024-06-26 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='currentdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
