# Generated by Django 5.0.6 on 2024-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_delete_worktypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskttransaction',
            name='state',
        ),
        migrations.AddField(
            model_name='taskttransaction',
            name='Status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='assign', max_length=50),
        ),
    ]
