# Generated by Django 4.2.1 on 2024-06-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_addmaterial_currentdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvedinquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotarea', models.IntegerField()),
                ('constructionarea', models.IntegerField()),
                ('constructioncost', models.IntegerField()),
                ('totalcost', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.client_registration')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.employeeregistration')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.worktypes')),
            ],
        ),
    ]
