# Generated by Django 5.0.6 on 2024-07-11 06:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_remove_taskttransaction_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterlabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField(default=datetime.datetime.now)),
                ('transfer_date', models.DateTimeField()),
                ('requirement_by', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.approvedinquiry')),
                ('requirement_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.employeeregistration')),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.site')),
            ],
        ),
        migrations.CreateModel(
            name='labourtransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('constructiontypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.constructiontype')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.masterlabour')),
            ],
        ),
    ]
