# Generated by Django 5.0.6 on 2024-07-26 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_masterlabour_labourtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategorys', models.CharField(max_length=100)),
                ('unitper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.brandlist')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.mastermateriallist')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.unitmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='selectproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitprice', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.FloatField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.brandlist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.mastermateriallist')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.approvedinquiry')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.site')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.unitmeasurement')),
                ('subcategorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_subcategories', to='construction.subcategory')),
            ],
        ),
    ]
